sudo: false

cache:
  directories:
    # Cache build artifacts to avoid constantly rebuilding. See:
    # https://8thlight.com/blog/rob-looby/2016/04/07/caching-elm-builds-on-travis-ci.html
    - elm-stuff/build-artifacts
    - examples/elm-stuff/build-artifacts
    # Install and cache sysconfcpus
    - sysconfcpus

env:
  matrix:
    - ELM_VERSION=0.19.0 TARGET_NODE_VERSION=node

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@elm$ELM_VERSION
  - npm install -g elm-format@elm$ELM_VERSION
  - npm install -g elm-test@elm$ELM_VERSION
  - cd example
  - elm make Translate.elm --output Main.html
  - cd ..

script:
  - elm make src/BinaryBase64.elm
  - elm-format --validate src/
  - elm-test
